#ifndef GAMEACTIONS_H
#define GAMEACTIONS_H

// debugging game actions
#define GAME_DEBUG_CAMERA_LEFT   5000
#define GAME_DEBUG_CAMERA_RIGHT  5001
#define GAME_DEBUG_CAMERA_UP	 5002
#define GAME_DEBUG_CAMERA_DOWN   5003

#define GAME_DEBUG_MOVE_LEFT	 6000
#define GAME_DEBUG_MOVE_RIGHT	 6001
#define GAME_DEBUG_MOVE_FORWARD	 6002
#define GAME_DEBUG_MOVE_BACKWARD 6003
#define GAME_DEBUG_MOVE_UP		 6004
#define GAME_DEBUG_MOVE_DOWN	 6005

#define GAME_DEBUG_INPUT_SPEED_INC 700
#define GAME_DEBUG_INPUT_SPEED_DEC 701

#endif